"""Add amount to a transaction history

Revision ID: 1b3f14efd36d
Revises: c5660032e66c
Create Date: 2021-07-16 16:22:51.149924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3f14efd36d'
down_revision = 'c5660032e66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walletTransactions', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walletTransactions', 'amount')
    # ### end Alembic commands ###
