"""Split wallet into own table

Revision ID: 4d63c8c02a0c
Revises: 4b5cd17a647c
Create Date: 2021-07-16 13:34:38.331153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d63c8c02a0c'
down_revision = '4b5cd17a647c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('transactionDate', sa.DateTime(), nullable=True),
    sa.Column('transactionType', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'wallet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_table('wallet')
    # ### end Alembic commands ###
