"""adjust portfolio FKs to link directly to a user

Revision ID: 4f642ecac675
Revises: e53aabdbd2d0
Create Date: 2021-07-19 12:45:56.287118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f642ecac675'
down_revision = 'e53aabdbd2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolioTransactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('portfolioTransactions_portfolio_id_fkey', 'portfolioTransactions', type_='foreignkey')
    op.create_foreign_key(None, 'portfolioTransactions', 'users', ['user_id'], ['id'])
    op.drop_column('portfolioTransactions', 'portfolio_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolioTransactions', sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'portfolioTransactions', type_='foreignkey')
    op.create_foreign_key('portfolioTransactions_portfolio_id_fkey', 'portfolioTransactions', 'portfolio', ['portfolio_id'], ['id'])
    op.drop_column('portfolioTransactions', 'user_id')
    # ### end Alembic commands ###
