"""newMigration

Revision ID: 5eb06bfa294e
Revises: ff0d604a75fc
Create Date: 2021-07-19 16:59:04.562992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb06bfa294e'
down_revision = 'ff0d604a75fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('name', sa.String(length=60), nullable=True))
    op.add_column('portfolioTransactions', sa.Column('name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolioTransactions', 'name')
    op.drop_column('portfolio', 'name')
    # ### end Alembic commands ###
