"""seperate out wallet transactions from the wallet

Revision ID: c5660032e66c
Revises: 2745f86112f2
Create Date: 2021-07-16 15:31:42.316463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5660032e66c'
down_revision = '2745f86112f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walletTransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('transactionDate', sa.DateTime(), nullable=True),
    sa.Column('transactionType', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('wallet', 'transactionDate')
    op.drop_column('wallet', 'transactionType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('transactionType', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('wallet', sa.Column('transactionDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('walletTransactions')
    # ### end Alembic commands ###
