"""add name prop to portfolio models to allow for more precise rendering

Revision ID: ff0d604a75fc
Revises: 4f642ecac675
Create Date: 2021-07-19 16:44:39.431830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0d604a75fc'
down_revision = '4f642ecac675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('name', sa.String(length=60), nullable=False))
    op.add_column('portfolioTransactions', sa.Column('name', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolioTransactions', 'name')
    op.drop_column('portfolio', 'name')
    # ### end Alembic commands ###
